# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Crypto Address')),
                ('coin_symbol', models.CharField(max_length=5, verbose_name='Coin Symbol')),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('usd_amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('fund_status', models.BooleanField(default=False, verbose_name='Funds Received')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Received Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
            },
        ),
    ]
