# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_store_name', models.CharField(max_length=100, unique=True)),
                ('seller_commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('seller_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('contact_methods', models.CharField(choices=[('ICQ', 'ICQ'), ('JABBER', 'JABBER'), ('TELEGRAM', 'TELEGRAM')], max_length=20)),
                ('contact_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellerTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('seller_current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller_previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_currency_type', models.CharField(choices=[('btc', 'Bitcoin'), ('ltc', 'Litecoin'), ('doge', 'Dogecoin')], default='btc', max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSellsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('CARD_DUMPS', 'DUMPS'), ('CARD_CVV', 'CVV'), ('CARDING_METHOD', 'METHOD'), ('SSN', 'SSN'), ('CARD_SCAN_DESIGNER', 'CARD SCAN')], max_length=20)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_placed_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_history', to='sellers.seller')),
            ],
        ),
    ]
