# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_start', models.CharField(max_length=20, unique=True)),
                ('bin_card_type', models.CharField(max_length=50)),
                ('bin_card_level', models.CharField(max_length=50)),
                ('bin_card_comptype', models.CharField(max_length=50)),
                ('bin_bank_name', models.CharField(max_length=100)),
                ('bin_country_name', models.CharField(max_length=50)),
            ],
        ),
    ]
