# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality_indicator', models.CharField(blank=True, help_text="Indicator of the category's item quality or validity.", max_length=3, null=True)),
                ('cards_available', models.IntegerField(default=0)),
                ('uploaded_cards', models.IntegerField(default=0)),
                ('sold_cards', models.IntegerField(default=0)),
                ('deleted_cards', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('category_status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', max_length=12)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller', verbose_name='Seller')),
            ],
        ),
    ]
