# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_card_identifier', models.CharField(max_length=100, unique=True, verbose_name='Unique Card Identifier')),
                ('card_info', models.CharField(max_length=500, verbose_name='Card Information')),
                ('card_bin', models.CharField(max_length=50, verbose_name='Card BIN')),
                ('card_expiry_month', models.IntegerField(verbose_name='Card Expiry Month')),
                ('card_expiry_year', models.IntegerField(verbose_name='Card Expiry Year')),
                ('card_holder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Holder Name')),
                ('card_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card City')),
                ('card_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card State')),
                ('card_zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card ZIP Code')),
                ('card_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Country')),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Brand')),
                ('card_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Type')),
                ('card_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Level')),
                ('card_bank', models.CharField(blank=True, max_length=200, null=True, verbose_name='Card Bank')),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Card Price')),
                ('card_publish_status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', max_length=20, verbose_name='Card Published Status')),
                ('card_category_published', models.BooleanField(default=False)),
                ('card_refund_status', models.PositiveSmallIntegerField(choices=[(1, 'With CheckTime'), (2, 'Buy & Check'), (7, 'No Refund')], default=1, verbose_name='Refund Status')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('in_cart', models.BooleanField(default=False)),
                ('cart_added_date', models.DateTimeField(blank=True, null=True)),
                ('card_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Base Name')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_cards', to='sellers.seller', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Credit Card Information',
                'verbose_name_plural': 'Credit Card Information',
            },
        ),
    ]
