# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(choices=[('BTC', 'Bitcoin'), ('LTC', 'Litecoin'), ('ETH', 'Ethereum'), ('DOGE', 'Dogecoin'), ('DASH', 'Dashcoin')], max_length=5)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('address_status', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coins', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_coins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
