# Generated by Django 4.2.1 on 2025-06-15 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_data', models.TextField(verbose_name='Card Data')),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Card Price')),
                ('status', models.CharField(choices=[('1', 'Bought'), ('2', 'Checking'), ('3', 'Approved'), ('4', 'Declined'), ('5', 'Fifty Code'), ('6', 'Time Out'), ('7', 'No Refund')], default='1', max_length=2, verbose_name='Order Status')),
                ('order_placed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Placed At')),
                ('order_updated_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Original Order ID')),
                ('buyer_username', models.CharField(max_length=150, verbose_name='Buyer Username')),
                ('seller_id', models.IntegerField(verbose_name='Seller ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Card Price')),
                ('final_status', models.CharField(max_length=50, verbose_name='Final Status')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Archived At')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyandcheck', models.BooleanField(default=False)),
                ('checker_name', models.CharField(default='LuxChecker', max_length=100)),
                ('auth_message', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.CharField(blank=True, max_length=100, null=True)),
                ('response_raw', models.TextField(blank=True, null=True, verbose_name='Raw Checker Response')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='orders.order')),
            ],
        ),
    ]
